apiVersion: v1
kind: Service
metadata:
  name: test-flask-app-service
spec:
  selector:
    app: test-flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
