name: flask app deployment to EC2

on:  
    push:  
      branches: [ "test" ]  
    pull_request:  
      branches: [ "main" ]  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO_NAME }}:latest .
        docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO_NAME }}:latest
    - name: Login to Amazon ECR
      run: >
        echo ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }} |
        aws --region ${{ secrets.AWS_REGION }} configure set aws_access_key_id "" --profile ecr-login &&
        aws --region ${{ secrets.AWS_REGION }} configure set aws_secret_access_key "" --profile ecr-login &&
        aws --region ${{ secrets.AWS_REGION }} ecr get-login-password --profile ecr-login | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}


    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO_NAME }}:latest
          docker stop ${{ secrets.CONTAINER_NAME }} || true
          docker rm ${{ secrets.CONTAINER_NAME }} || true
          docker run -d --name ${{ secrets.CONTAINER_NAME }} -p 80:5000 ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO_NAME }}:latest