name: flask app deployment to ACI

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

env:
  REGISTRY_NAME: sooregi
  CLUSTER_NAME: sooaks
  CLUSTER_RESOURCE_GROUP: soo-rg
  NAMESPACE: default

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/flaskapp:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/flaskapp:${{ github.sha }}

    deploy:
        needs: build
        runs-on: ubuntu-latest
        environment: production
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Set AKS cluster'
          uses: azure/aks-set-context@v1
          with:
            creds: '${{ secrets.AZURE_CREDENTIALS }}'
            cluster-name: ${{ env.CLUSTER_NAME }}
            resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
        
        # Create namespace if doesn't exist
        - run: |
            kubectl create namespace ${{ env.NAMESPACE }} --dry-run -o json | kubectl apply -f -

        # Create imagepullsecret for Azure Container registry (ACR)
        - uses: azure/k8s-create-secret@v1
          with:
            container-registry-url: ${{ env.REGISTRY_NAME }}.azurecr.io
            container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
            container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            secret-name: ${{ env.REGISTRY_NAME }}-registry-connection
            namespace: ${{ env.NAMESPACE }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/flaskapp:${{ github.sha }}
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: test-flask-app
            location: 'korea central'

        # - name: 'Deploy to AKS'
        #   uses: Azure/k8s-deploy@v4.9
        #   with:
        #     manifests: |
        #       manifests/flask-app.yaml
        #     images: |
        #       ${{ secrets.REGISTRY_LOGIN_SERVER }}/flaskapp:${{ github.sha }}
        #     imagepullsecrets: |
        #       ${{ env.REGISTRY_NAME }}-registry-connection
        #     namespace: ${{ env.NAMESPACE }}

        - uses: azure/k8s-set-context@v1
          with:
            kubeconfig: ${{ secrets.KUBE_CONFIG }}